import './global.css';
import { PageWrapper } from '@rad/app-ui';

export const metadata = {
  title: 'Welcome to to-do-list',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h1>To do list</h1>
        <PageWrapper>{children}</PageWrapper>
      </body>
    </html>
  );
}
